name: Dependency sanity checker

on:
  push:
    branches: [main, release/**]
#  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  dependency-sanity-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: scripts/check-dependencies.bash
  validate-rust-git-rev-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stellar/actions/rust-check-git-rev-deps@main
