name: Docs validation

on:
  push:
    branches: [main, release/**]
  pull_request:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  docs-validation:
    uses: stellar/stellar-docs/.github/workflows/build.yml@main
    with:
      stellar-cli-ref: ${{ github.sha }}
