name: Update CompletedSprint on Issue Closed

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed, comment]

jobs:
  update-completed-sprint:
    runs-on: ubuntu-latest
    steps:
      - uses: stellar/actions/update-completed-sprint-on-issue-closed@main
        with:
          project_name: "Platform Scrum"
          field_name: "CompletedSprint"
          project_token: ${{ secrets.GHPROJECT_TOKEN }}
